### PR TITLE
VS2019 + WiX Installer, a new approach

### LINKED ISSUE #115: Windows installation path
For now Windows installer put the application to `C:\Program Files\Fips-3.a.b`. I think, that user predicts that new program installation will rewrite old one. Should we change the path to `C:\Program Files\Fips-3`? This will prevent corruption of user's scripts and aliases after update.

### PR DESCRIPTION
**Pull request by ForNeVeR**
This is the same as #150, but uses lighter approach (VC++ Runtime DLL should be included by default, but it won't deal with UCRT, which I now consider as acceptable).

Closes #115.

### CODE REVIEW

**Comment by matwey** [comment]
Windows 10 works fine for me. Windows 7 also works if KB2999226 update (UCRT) is installed. 

What do you think, is it possible to check if the update is installed and show error during installation? I have found similar snippet:
https://github.com/dokan-dev/dokany/issues/135#issuecomment-171266590

**Comment by ForNeVeR** [comment]
The check in the post you linked doesn't look good to me. I'm not sure if it is reliable enough, the versions they're listing look pretty random. Also, it's possible to have part of ucrt DLLs and not have other ones (which is I think happening on some versions of Windows 10). I'd put that aside. Let's just ask people to update their stuff.

**Comment by matwey** [comment]
Ok then. Is it ready to merge?

**Comment by ForNeVeR** [comment]
Yas.

**Comment by matwey** [comment]
Good, thanks

**Pull request merged**
