### PR TITLE
Update deploy auth_token in .appveyor.yml

### LINKED ISSUE #157: Appveyor release deploy failed
Currently, I see the following in Appveyor CI:

```
Uploading artifacts...
[1/1] Fips-3.4.0-win64.msi (22,282,240 bytes)...100%
Deploying using GitHub provider
Creating "3.4.0" release for repository "matwey/fips3" tag "3.4.0" commit "f68ca188b55d0f339f4849f10c38c2d65f3d11c1"...Error creating GitHub release: Error reading repository 'matwey/fips3' releases: 401 - Unauthorized
```

Probably, the keys or tokens are expired for some reason.

### PR DESCRIPTION
**Pull request by matwey**
Close #157

Check this GUI features before merge:

- [ ] Positive and negative `BITPIX` images
- [ ] Zoom, rotate and flip
- [ ] Level control
- [ ] Color maps
- [ ] Open new image in the same window and in new window

### CODE REVIEW

**Comment by ForNeVeR** [comment]
I recommend creating and pushing a temporary tag to check if the release will work this time.

**Comment by matwey** [comment]
> I recommend creating and pushing a temporary tag to check if the release will work this time.

Assuming that @hombit will fix #156, it is probably better to test them together.

**Comment by ForNeVeR** [comment]
Since this is a separate pull request, I suggest separate testing for it. Also, it shouldn't be hard: just push the tag and check the CI.

**Comment by matwey** [comment]
> Since this is a separate pull request, I suggest separate testing for it. Also, it shouldn't be hard: just push the tag and check the CI.

I've checked that deploying is working now.

**Pull request merged**
