### PR TITLE
Implement 3D movie support

### PR DESCRIPTION
**Pull request by matwey**
Check this GUI features before merge:

- [x] Positive and negative `BITPIX` images
- [x] Zoom, rotate and flip
- [x] Level control
- [x] Color maps
- [x] Open new image in the same window and in new window

Check also the following.
While 3D image is opened
- [x] Load new 2D in this window while playing
- [x] Load new 2D in this window while pause
- [x] Load new 3D in this window while playing
- [x] Load new 3D in this window while pause

While 2D image is opened
- [x] Load new 3D in this window

### CODE REVIEW

**Comment by matwey** [comment]
This pull request **introduces 1 alert** when merging 8230f70f655ed3f8c1196092921515a6047bea26 into bbdfcfb50401964f3830da954adbe43ba5af81ab - [view on LGTM.com](https://lgtm.com/projects/g/matwey/fips3/rev/pr-80f4cf38c0a98a76205a72558d991a7a5ea8b876)

**new alerts:**

* 1 for Missing header guard

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by matwey** [comment]
This pull request **introduces 1 alert** when merging bebad364cbf39c12ca1ada2165d35ef1a6ad2346 into 00c789d8e790aa63a510d9988653c7da36f6cf27 - [view on LGTM.com](https://lgtm.com/projects/g/matwey/fips3/rev/pr-b3db344dfe898e85d9185ef8a31afb81c48e97ad)

**new alerts:**

* 1 for Missing header guard

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by matwey** [comment]
This pull request **introduces 1 alert** when merging 1eea345bda3d4534f6e041987dbb3e72e7217fcf into 00c789d8e790aa63a510d9988653c7da36f6cf27 - [view on LGTM.com](https://lgtm.com/projects/g/matwey/fips3/rev/pr-7729552084fa12e1799a1ec36bc9fdd0e63b9710)

**new alerts:**

* 1 for FIXME comment

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by matwey** [comment]
@hombit shall we also generate 3D test data for `test/data`?

**Comment by hombit** [comment]
We should add:

- [ ] OpenGL 2 support
- [ ] Dock widget improvements: interval/fps setter, frame counter, etc

**Comment by matwey** [comment]
Yet another issue with this PR is that we must handle `GL_MAX_ARRAY_TEXTURE_LAYERS` gracefully. It is issue similar to #47

**Pull request merged**
